import os
from pathlib import Path
import re
import subprocess

FILES = {
    "init":   "initialize_core.txt",
    "branch": "branch_core_code.txt",
    "leaf":   "leaf_core_code.txt",
}

STOP_MARKER = "DO NOT INCLUDE LINES BELOW THIS AS PULLED FROM DRAM"
HEX_SECTION = "============ HEX ============"

def parse_hex_file(filename: str) -> list[str]:
    """
    Parse a hex output file, returning raw lines (with comments) between
    the HEX section header and the DO NOT INCLUDE marker (inclusive of the
    marker line).
    """
    lines = []
    in_hex_section = False

    with open(filename, "r") as f:
        for raw in f:
            line = raw.rstrip()

            if HEX_SECTION in line:
                in_hex_section = True
                continue

            if not in_hex_section:
                continue

            # Skip blank lines
            if not line.strip():
                continue

            lines.append(line)

            # Stop AFTER including the marker line
            if STOP_MARKER in line:
                break

    return lines


def make_rust_fn(fn_name: str, array_name: str, lines: list[str]) -> str:
    count = len(lines)
    # Extract just the hex value (first token before comma or end)
    indent = "        "
    entries = []
    for line in lines:
        # Each line looks like:  0xDEADBEEF,   //PC = ...
        # Grab the hex value and the comment separately
        m = re.match(r"\s*(0x[0-9A-Fa-f]+),?\s*(//.*)?", line)
        if m:
            val = m.group(1)
            comment = m.group(2) or ""
            entries.append(f"{indent}{val}, {comment}".rstrip())
        else:
            # Fallback: include line as-is inside a comment
            entries.append(f"{indent}// (unparsed) {line.strip()}")

    body = "\n".join(entries)
    if fn_name == "get_init_vector":
        return f"""\
    pub fn {fn_name}() -> Vec<u32> {{
        let mut {array_name}: [u32; {count}] = [
    {body}
        ];
        {array_name}[0] = {array_name}.len() as u32 - 1;
        {array_name}.to_vec()
    }}"""

    return f"""\
    pub fn {fn_name}() -> Vec<u32> {{
        let mut {array_name}: [u32; {count}] = [
    {body}
        ];
        {array_name}.to_vec()
    }}"""


def run_and_capture(src_file: str, out_path: str) -> None:
    """
    Executes `cargo run <src_file>` and writes the command’s stdout to *out_path*.
    The output file (and any missing parent directories) are created automatically.
    """
    out_file = Path(out_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    with out_file.open("w") as fh:
        subprocess.run(
            ["cargo", "run", src_file],
            stdout=fh,
            check=True,
        )


def main():
    parsed = {}
    import shutil

    shutil.copy2(
        "../../../rust_rt_arch_sim/src/run.log",
        "../../../rust_rt_arch_sim/src/backup_run.log"
    )
    run_and_capture("initialize_core.s", "initialize_core.txt")
    run_and_capture("branch_core_code.s", "branch_core_code.txt")
    run_and_capture("leaf_core_code.s",   "leaf_core_code.txt")

    for key, filename in FILES.items():
        print(f"Parsing {filename}...")
        parsed[key] = parse_hex_file(filename)
        print(f"  -> {len(parsed[key])} entries")

    rust_code = "// Auto-generated by gen_matricies.py\n\n"
    rust_code += make_rust_fn("get_init_vector",      "init_vector",   parsed["init"])
    rust_code += "\n\n"
    rust_code += make_rust_fn("get_branch_core_code", "branch_vector", parsed["branch"])
    rust_code += "\n\n"
    rust_code += make_rust_fn("get_leaf_core_code",   "leaf_vector",   parsed["leaf"])
    rust_code += "\n"

    out = "../../../rust_rt_arch_sim/src/auto_gen_code.rs"
    with open(out, "w") as f:
        f.write(rust_code)
    print(f"\nWrote {out}")

    # subprocess.run(
    #     ["cargo", "run", "2>&1", "|", "tee", "run.log"],
    #     cwd=os.path.join(os.path.dirname(__file__), "..", "..", "..", "rust_rt_arch_sim", "src")
    # )
    import sys

    sim_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "rust_rt_arch_sim", "src")
    log_path = os.path.join(sim_dir, "run.log")

    with open(log_path, "w") as log_file:
        proc = subprocess.Popen(
            ["cargo", "run"],
            cwd=sim_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        for line in proc.stdout:
            decoded = line.decode()
            sys.stdout.write(decoded)
            log_file.write(decoded)
        proc.wait()


if __name__ == "__main__":
    main()